baseURL = 'https://ewanjones.dev/'
languageCode = 'en-us'
title = 'Ewan Jones'
theme = "dev"

# Makes the menus appear based on the directories in `content`
sectionPagesMenu = "main"

[params]
  favicon = ""
  site_logo = ""
  description = "A London-based developer, (soon to be) pilot and music nerd"

  custom_css = ["css/special.css"]

  # Links in header and footer
  twitter = "https://twitter.com/ewanglynjones"
  instagram = "https://www.instagram.com/joneseg/"
  github = "https://github.com/ewanjones/"
  linkedin = "https://www.linkedin.com/in/ewan-jones/"

  background_color_class = "bg-dark-gray"
  featured_image = "/images/plane-background.jpg"
  recent_posts_number = 2

  # Post page
  show_reading_time = true
