baseURL = 'https://ewanjones.dev/'
languageCode = 'en-us'
title = 'Ewan Jones'
theme = "dev"

# Makes the menus appear based on the directories in `content`
sectionPagesMenu = "main"
summaryLength = 50


[params]
  favicon = ""
  site_logo = ""
  description = "A London-based developer, pilot and music enthusiast"

  # Tell the theme which sections are considered the main ones (e.g. should show recent posts)
  mainSections = ["writing"]
  recentPostsNumber = 3

  custom_css = ["css/special.css"]

  # Links in header and footer
  twitter = "https://twitter.com/ewanjonesdev"
  instagram = "https://www.instagram.com/joneseg/"
  github = "https://github.com/ewanjones/"
  linkedin = "https://www.linkedin.com/in/ewan-jones/"

  background_color_class = "bg-dark-gray"
  featured_image = "/images/plane-background.jpg"
  recent_posts_number = 2

  # Post page
  show_reading_time = true

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'babel']


[taxonomies]
  category = "categories"

[markup.goldmark.renderer]
  # Allow raw HTML in markdown files
  unsafe = true
